project: 
  type: website
  output-dir: docs

website: 
  page-navigation: true
  title: "StatePol Database" 
  site-url: "https://github.com/StatePol/Database" 
  repo-url: https://github.com/StatePol/Database 
  repo-actions: [edit, issue]
  search: 
    location: navbar
    type: overlay

# page bottom formatting
  page-footer:
    left: "&copy; StatePol 2023"

# navbar (top) formatting
  navbar:
    background: "#9DB4C0"
    right:
      - href: index.qmd
        text: Home
      - href: applications.qmd
        text: Applications
      - href: sources.qmd
        text: Sources
      - href: authors.qmd
        text: Team
      
        
# side bar formatting
  sidebar:
  - id: Home
    logo: "images/hex_statepol.png"
    pinned: true
    align: center
    tools: 
      - icon: book
        href: https://link.springer.com/book/10.1007/978-3-658-29222-5
      - icon: github
        href: https://github.com/StatePol/Database
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
  
  - id: Applications
    contents:
      - href: applications.qmd
        text: Applications
        
  - id: Sources
    contents:
      - href: sources.qmd
        text: Sources
        
  - id: Team
    contents:
      - href: authors.qmd
        text: Team
  



format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true